### PR TITLE
Added drop down menu to magazine covers.

### PR DESCRIPTION
**Pull request by JBigs206**
Added a drop down menu associated with each magazine issue. The drop down menu provides individual links to view the poems that were featured in that magazine issue.

### CODE REVIEW

**Comment by ghost** [comment]
We could reduce a click by making the dropdown show on hover. Not a high priority, but a good small UX improvement.

**Comment by tynanook** [comment]
@JBigs206 @wibblywink 
I see you link to 'magazine.html'. Is this different than a single poem? The way I understand it, the image is a magazine, but the list of poems that show at the bottom of the image are poems, not a magazine. If this is correct, the list items should link to 'poem.html'.

Otherwise, good job. I know you were waiting for the 'poem.html' being created, so I see no issues with your code. I'd make this simple change and then I'm fine with merging your branch into the master.

I did notice a strange issue with the navigation. I wouldn't say its your navigation link that is the issue. However, I did see if the 'dropdown' navigation button is selected (not your magazine nav button, but the actual 'dropdown' button in the navbar, the link to your navbar 'magazine' button will no long function. I don't feel this is button with your button, but is perhaps related to the overall navigation code. More research is required to understand this, as it is an issue. please note this.

**Comment by yuens1002** [comment]
jeff, thanks for the page.  a few suggestions.  after thinking about it from your other issue as well, adding a header for the current issue would be a good anchor for the user to indicate the current page they're in and give the current issue more visual interest.  style the magazine top nav and add side nav would be nice.

**Comment by JBigs206** [comment]
@wibblywink @yuens1002 @tynanook Thanks all for the suggestions! I've added suggested changes from both the DisplayMag and dropDownMenu code reviews. I will be merging these changes to the master branch.

**Pull request merged**
