### PR TITLE
sign in modal

### PR DESCRIPTION
**Pull request by yuens1002**
**WORK**
1. created a modal in index.html
2. linked the sign in button and link at the bottom of the page to trigger modal
3. linked the sign in button in modal to profile.com
4. linked main.css
5. moved inline header css to main.css
6. modified theme-bootstrap to show modal on top of background.

**DESC**
I mentioned making a sign in page in the user story for this issue.  After some thinking, I decided to create a modal instead because a modal makes more sense. It keeps the user on the same page he/she is current visiting and it accomplishes the task with less code.

### CODE REVIEW

**Comment by ghost** [comment]
I like the modal a lot. There are quite a few views for this site, so it was a nice experience to have a modal here rather than another page.
Ok to merge.

**Comment by ghost** [comment]
@yuens1002 Your comments/descriptions on the pulls are really helpful. It made going through the pages and code much easier having that reference.

**Comment by tynanook** [comment]
@yuens1002 I agree with Maggie's comments. Your comments helped review your issue relatively quickly. 
Your modal looks fine and works well with the site.
I also approve this pull request for merging.

**Comment by JBigs206** [comment]
Sign in modal looks good. I also like your decision to switch from a sign in page to just a modal. Definitely makes more sense. I'm fine with this being merged.

**Pull request merged**
